### ISSUE TITLE
.rubocop.yml needs appropriate defaults now that we're off standard.

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/argo#4214]
With PR #4200, we ended up with a `.rubocop.yml` that does not exclude enough directories (it takes many minutes to run rubocop when you have no local rubocop cache for Argo (e.g. after updating the rubocop gem)).   It also put EVERYTHING into .rubocop_todo.yml, which may be less troubling:

```
require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: disable
  Exclude:
    - bin/**
    - vendor/bundle/**/*

inherit_from:
  - .rubocop_todo.yml
```

That's it.  Any of our local changes to default settings don't show.

The work for this PR:
- [x] expand what files are excluded to be more reasonable.  tmp, logs, lock files, build directories.  
     ```
  Exclude:
    - bin/**
    - db/migrate/**
    - db/schema.rb
    - vendor/bundle/**/*
    - node_modules/**/*
    - tmp/**/*
    - log/**/*
    - fedora_conf/**/*
    - public/**/*
    - coverage/**/*
    - postgres-data/**/*
    - spec/fixtures/**/*
   ``` from https://github.com/sul-dlss/argo/pull/3877/files
- [ ] add back rules we know we don't like, e.g. LineLength.   

You might 
a) look at rubocop.yml from before we went to standard:  https://github.com/sul-dlss/argo/pull/3877/files
b) see https://github.com/sul-dlss/DeveloperPlaybook/blob/main/style/infra_template.rubocop.yml
c) look at another app with a UI, such as ETD or PreAssembly and take appropriate settings from that. (Note that h2 uses standard.)
