### ISSUE TITLE
Navigation from one collection member to all collection members

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#449]
When a user goes to an individual object, it would be nice to have two options:
1. the user can link to the collection object (this currently exists)
2. the user can link to all objects in the collection to which the object belongs (new feature) – this is currently a two-step process and would improve speed moving between individual objects and all of its fellow children.

transferred from https://jirasul.stanford.edu/jira/browse/ARGO-488

**Comment by blalbrit** [comment]
Additional comments from Arcadia that expands the nature of this ticket in a logical way:

It would be great if there were a “See objects in this collection” link on a collection object that would return a search-result view as if the user had clicked on the corresponding collection facet value from the home page. Currently the user has to note the collection of the object, open the home page, open the appropriate facet, choose see all, and then ctrl-f to find the collection (with a couple of extra steps if it’s a Hydrus collection).
 
Ditto for APOs.

**Comment by justinlittman** [comment]
I'm stuck on how to handle this in spec:
```
Failures:

  1) ValueHelper#links_to_collections creates multiple links delimited by a line break
     Failure/Error: objs_link = link_to('All objects in this collection', path_for_facet('nonhydrus_collection_title_ssim', collection_pid))
     
     NameError:
       undefined local variable or method `blacklight_config' for #<#<Class:0x00007fdecd365610>:0x00007fded5de12d0>
       Did you mean?  blacklight
     # ./app/helpers/value_helper.rb:76:in `block in links_to_collections_with_objs'
     # ./app/helpers/value_helper.rb:70:in `map'
     # ./app/helpers/value_helper.rb:70:in `with_index'
     # ./app/helpers/value_helper.rb:70:in `links_to_collections_with_objs'
     # ./app/helpers/value_helper.rb:61:in `links_to_collections'
     # ./spec/helpers/value_helper_spec.rb:27:in `block (3 levels) in <top (required)>'
```

`path_for_facet()` comes from [facets_helper_behavior()](https://github.com/projectblacklight/blacklight/blob/3a04827dfa46fc8dbfd582575bf96ff9b88255de/app/helpers/blacklight/facets_helper_behavior.rb#L138) which uses [facet_configuration_for_field](https://github.com/projectblacklight/blacklight/blob/c2c979040d31aa582fd9b4d1121d8bc924008b88/app/controllers/concerns/blacklight/facet.rb#L7), which is delegated to blacklight_config.
