### ISSUE TITLE
revisit pending and skipped tests

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/argo#556]
almost nice as a passing test suite with good coverage is a passing test suite with good coverage and few to no pending and skipped tests.  we should do some fixing of pending and skipped tests in argo when we have the time.

motivated by discussion on https://github.com/sul-dlss/argo/pull/541

**Comment by aaron-collier** [comment]
Current pending tests:

```
Pending: (Failures listed here are expected and do not affect your suite's status)

  1) DorObjectHelper does not have any tests
     # Not yet implemented
     # ./spec/helpers/dor_object_helper_spec.rb:6

  2) RegistrationController#autocomplete has no spec yet
     # No reason given
     # ./spec/controllers/registration_controller_spec.rb:329

  3) Bulk Descriptive Metadata Download Populate druids from last search
     # not implemented spec due to js testing restrictions
     Failure/Error: fail
     RuntimeError:
     # ./spec/features/bulk_desc_metadata_download_spec.rb:23:in `block (2 levels) in <top (required)>'

  4) mods_view item dialogs register loads the registration form
     # appears to pass even if blacklight JS isn't included in application.js or register.js, which you'd expect to break things. skipping since it might be useless anyway.
     # ./spec/features/item_displays_spec.rb:128
```
